<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>...:::CONSULTAR USUARIO:::...</title>
</head>

<body>
<div>
<div>
<p>Fecha y hora:</p>
<h1 align="center">CONSULTAR CONTACTO</h1>
<p>Usuario:</p>
</div>
<div align="center">
<hr />
<table width="290" border="0">
  <tr>
    <td width="147" align="right">Tipo de búsqueda:</td>
    <td width="133"><label>
      <select name="select" id="select">
        <option>-seleccione-</option>
        <option>Masiva</option>
        <option>Recurrente</option>
      </select>
    </label></td>
  </tr>
  <tr>
    <td align="right">Buscar por:</td>
    <td><label>
      <select name="select2" id="select2">
        <option selected="selected">-seleccione-</option>
        <option>Nombre</option>
        <option>Apellido</option>
</select>
    </label></td>
  </tr>
  <tr>
    <td align="right">Valor:</td>
    <td><label>
      <input type="text" name="textfield" id="textfield" />
    </label></td>
  </tr>
</table>
</div>
<div align="center">
<hr />
<table width="200" border="1">
  <tr>
    <td>Nº</td>
    <td>Nombre</td>
    <td>Apellido</td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
</div>
<div align="center">
<hr />
<table width="200" border="0">
  <tr>
    <td align="center"><img src="imagenes/consultar.png" width="150" height="48" /></td>
    <td align="center"><img src="imagenes/cancelar.png" width="150" height="48" /></td>
  </tr>
</table>
</div>
</div>
</body>
</html>
